add main logic for script (not tested)
UWARG/signal-strength-logging pull request #2
Opened 2024-02-09 02:57 UTC by maxlou05

2024-02-09 04:10 UTC, mgupta27 approved these changes
Conditionally approve.

Please write a rc.local.copyme that contains the command to run the code.

2024-02-17 04:24 UTC, Xierumeng reviewed
Reviewed.

2024-02-17 04:24 UTC, Xierumeng commented on rc.local.copyme
> +python3 signal_strength_tracker.py &
Is the user home directory the default for `rc.local` ? I recommend an absolute path.

Also, virtual environment?

2024-02-17 04:24 UTC, Xierumeng commented on requirements.txt
> +
Remove empty line.

2024-02-17 04:24 UTC, Xierumeng commented on signal_strength_tracker.py
> +# Wait 20 seconds becasue the RPi has a setting where it doesn't boot until 20 seconds after power
Add a main guard.

2024-02-17 04:24 UTC, Xierumeng commented on signal_strength_tracker.py
> +time.sleep(20)
Make this value a global constant.

2024-02-20 00:41 UTC, Xierumeng reviewed
Reviewed.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +# Parameters
Remove, unnecessary.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +SERIAL_PORT = "/dev/ttyUSB3"  # Change this to match your modem's serial port
Remove 2nd person references (i.e. replace with `the` ).

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +SERIAL_PORT = "/dev/ttyUSB3"  # Change this to match your modem's serial port
Is modem referring to the LTE device?

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +BAUDRATE = 115200  # Change this to match your modem's baud rate
Same as above.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +AT_COMMAND = b"AT+CSQ\r\n"  # Command to run on modem
What does this command do?

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +OUTPUT_LOG_FILE_PATH = pathlib.Path(f"/media/warg/E3F9-7EE3/signal_log_{int(time.time())}.txt")
Separate each directory as an argument. For example:
```py
pathlib.Path("/", "absolute", "path", "to", "file.txt")
```

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +PERIOD = 3
Add empty line above this line.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +PERIOD = 3
Add comment: `# seconds`

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +SETUP_TIME = 20
Add comment: `# seconds`

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +SETUP_TIME = 20
Move this above line 16.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +
2 empty lines between global constants and top level functions.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +    # Wait 20 seconds becasue the RPi has a setting where it doesn't boot until 20 seconds after power
Remove or move to the constant.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +    # Wait 20 seconds becasue the RPi has a setting where it doesn't boot until 20 seconds after power
Is it the Raspberry Pi itself that doesn't boot for 20 seconds? If the Raspberry Pi isn't booted how is the program supposed to run? Is it something else that isn't booting immediately?

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +        log_file = open(OUTPUT_LOG_FILE_PATH, 'a')
Add: `, encoding="utf-8"`

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +            timeout=1,
Make this a global constant.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +        response = ser.read(1000)
Make this a global constant.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +            "    Response: " + response.decode('utf-8') + "\n"
Use double quotation marks.

2024-02-20 00:41 UTC, Xierumeng commented on signal_strength_tracker.py
> +        ser.close()
Any particular reason why the file and serial port is being opened and reclosed on every iteration of the loop?

2024-02-20 00:43 UTC, Xierumeng requested changes
I am blocking the merge until the environment is resolved.

2024-02-20 00:43 UTC, Xierumeng commented on rc.local.copyme
> +python3 signal_strength_tracker.py &
See the other repositories for better examples of `rc.local.copyme` .

2024-02-20 06:22 UTC, Xierumeng reviewed
Reviewed.

2024-02-20 06:22 UTC, Xierumeng commented on rc.local.copyme
> +python3 /home/warg/signal_strength_tracker.py &
Add virtual environment activation.

2024-02-20 06:22 UTC, Xierumeng commented on signal_strength_tracker.py
> +TIMEOUT = 1  # Seconds
More descriptive variable name (e.g. `SERIAL_INITIALIZATION_TIMEOUT` ).

2024-02-20 06:22 UTC, Xierumeng commented on signal_strength_tracker.py
> +BYTES_TO_READ = 1000  # Maximum bytes to read after command is run
More descriptive variable name (e.g. `MAX_BYTES_TO_READ` ).

2024-02-20 06:22 UTC, Xierumeng commented on signal_strength_tracker.py
> +SETUP_TIME = 20  # Wait 20s since the RPi has a setting where it doesn't boot until 20s after power
Where is this setting? Add the information to the Confluence documentation and reference it (e.g. `See documentation for more detail` ).

2024-02-22 23:33 UTC, Xierumeng reviewed
Reviewed. Alternatively, create `run.sh` to be called.

2024-02-22 23:33 UTC, Xierumeng commented on rc.local.copyme
> +cd /home/warg/venv
`cd /home/warg/signal-strength-logging/`

2024-02-22 23:33 UTC, Xierumeng commented on rc.local.copyme
> +source bin/activate
`source venv/bin/activate`

2024-02-22 23:33 UTC, Xierumeng commented on rc.local.copyme
> +python3 /home/warg/signal_strength_tracker.py &
`python -m signal-strength-tracker`

`&` optional.

2024-02-23 04:06 UTC, Xierumeng approved these changes
Approved.

2024-02-23 16:37 UTC, merged